version: '3.6'
services:
  iris:
    build: 
      context: ./iris
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773:51773
      - 52773:52773 
    volumes: 
      - ./:/irisdev/app
  jupyter:
    build: 
      context: ./py
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 8888:8888
    volumes: 
      - ./Examples:/home/jovyan/work